### ISSUE TITLE
Program Error in the Email Notification Plugin

### ISSUE THREAD

**Issue by gildegoma** [swisstxt/onduty#2]
Error message:

```
Onduty::Notification: Error sending email: undefined method `email' for nil:NilClass
```

**Note:** not urgent since this plugin will be disabled (superseeded by Zendesk Ticket creation, which also generate an e-mail notification)

**Comment by niwo** [comment]
It seems you hit a corner case where the contact class is not initialized.
You should check if one of your groups is empty.
To prevent this case, one could set a default contact in the "set_group_and_contact" method (/lib/onduty/notification.rb).

**Comment by gildegoma** [comment]
@niwo thank you for the insight. Indeed, I'll make it a bit more robust as you recommend, but I'm still curious to understand why the bug occurred (since no contact in MongoDB lacks of email property, and both groups had an active onduty). Anyway, it's not urgent, but looking forward to fix it :stuck_out_tongue_winking_eye:
